Update rootless docker images to the latest
craftercms/docker-images pull request #89
Opened 2024-03-13 03:22 UTC by phuongnq

https://github.com/craftercms/craftercms/issues/6621

2024-03-27 20:48 UTC, avasquez614 requested changes
@phuongnq I think we need a rootless brach for 4.1 too

2024-04-09 06:39 UTC, phuongnq commented
@avasquez614 This is actually for 4.1.x. I have updated the default flag to 4.1.4
As of current, we don't have any difference between 4.1 and develop branch. When we have the new Spring 6 PRs merge, it could be changed though (since Spring 6 uses Tomcat 10)

2024-04-09 13:50 UTC, sumerjabri requested changes
I updated the base to use Tomcat 9.0.86, please do the same.

https://github.com/craftercms/docker-images/pull/90/files

2024-04-09 13:50 UTC, sumerjabri commented on images/authoring_local/tomcat/Dockerfile
> +    TOMCAT_VERSION="9.0.85"
9.0.86?

https://github.com/craftercms/craftercms/blob/support/4.1.x/pom.xml#L187

2024-04-09 13:50 UTC, sumerjabri commented on images/delivery/tomcat/Dockerfile
> +    TOMCAT_VERSION="9.0.85"
.86

2024-04-10 07:28 UTC, phuongnq commented on images/authoring_local/tomcat/Dockerfile
> +    TOMCAT_VERSION="9.0.85"
Updated

2024-04-10 07:28 UTC, phuongnq commented on images/delivery/tomcat/Dockerfile
> +    TOMCAT_VERSION="9.0.85"
Updated

2024-04-10 13:05 UTC, avasquez614 approved these changes

2024-04-15 23:35 UTC, sumerjabri approved these changes

2024-04-15 23:35 UTC, merged